AssoFlex/Models/Utilisateur.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Reflection.Metadata;

namespace AssoFlex.Models
{
    public class Utilisateur
    {
        public int Id { get; set; }
        public string Genre { get; set; }
        [MaxLength(25)]
        public string Prenom { get; set; }
        [MaxLength(30)]
        public string Nom { get; set; }
        public int NomComplet { get; set; }
        [MaxLength(80)]
        public string Adresse { get; set; }
        
        public int Telephone { get; set; }
        [MaxLength(50)]
        [Required]
        [DataType(DataType.EmailAddress)]
        [EmailAddress]

        public string Email { get; set; }
       

        [MaxLength(100)]
        [Required]
        public string Password { get; set; }
        [MaxLength(12)]
        public string Role { get; set; }
        public string ProfilImg { get; set; }
        // public List<Association> UserAssociations { get; set; }

    }

    public enum Genre
    {
        Homme,
        Femme
    }
}

AssoFlex/ViewModels/UtilisateurViewModel.cs
using AssoFlex.Models;
using Microsoft.AspNetCore.Http;

namespace AssoFlex.ViewModels
{
    public class UtilisateurViewModel
    {
        public Utilisateur Utilisateur { get; set; }
        public IFormFile ProfilImg { get; set; }
        public bool Authentifie { get; set; }
    }
}

AssoFlex/Controllers/UtilisateurController.cs
using System.Collections.Generic;
using System.Linq;
using AssoFlex.Models;
using Microsoft.AspNetCore.Mvc;
using Controller = Microsoft.AspNetCore.Mvc.Controller;

namespace AssoFlex.Controllers
{
    public class UtilisateurController : Controller
    {
        private IDal _dal;

        public UtilisateurController()
        {
            this._dal = new Dal();
        }

        public IActionResult GetUtilisateur(int id)
        {
            Utilisateur user = _dal.GetUtilisateur(id);
            return View(user);
        }

        public IActionResult GetAdhesions(int id)
        {
            List<Adhesion> allAdhesions = _dal.GetAllAdhesions();
            List<Adhesion> listeAdhesion = allAdhesions.Where(adhesion => adhesion.UtilisateurId == id).ToList();
            return View(listeAdhesion);
        }

        public IActionResult GetEvenements(int id)
        {
            List<Reservation> allReservations = _dal.GetAllReservations();
            List<Reservation> listReservations = allReservations.Where(e => e.UserId == id).ToList();
            return View(listReservations);
        }
        
        public IActionResult GetCrowdfundings(int id)
        {
            List<Contribution> allContributions = _dal.GetAllContributions();
            List<Contribution> listContributions = allContributions.Where(e => e.utilisateurId == id ).ToList();
            return View(listContributions);
        }

        public IActionResult DeleteUtilisateur(int id)
        {
            this._dal.DeleteUtilisateur(id);
            return RedirectToAction("DashboardAdmin", "Dashboard");
        }

        public IActionResult UpdateUtilisateur(int id, string prenom, string nom, string adresse,
            int telephone, string email, string password, string role)
        {
            Utilisateur user = this._dal.GetUtilisateur(id);
            return View(user);
        }

        [Microsoft.AspNetCore.Mvc.HttpPost]
        public IActionResult UpdateUtilisateur(Utilisateur user)
        {
            if (ModelState.IsValid)
            {
                this._dal.UpdateUtilisateur(
                    user.Id, user.Prenom, user.Nom, user.Adresse, user.Telephone,
                    user.Email, user.Password, user.ProfilImg,user.Role);
                return RedirectToAction("DashboardAdmin", "Dashboard");
            }

            return View("Error");
        }
    }
}

AssoFlex/Views/Utilisateur/GetAdhesions.cshtml
@using System.Security.Claims
@model System.Collections.Generic.List<AssoFlex.Models.Adhesion>

@{
    ViewBag.Title = "Adhésions";
    Layout = "_LayoutDashboard";
}
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <i class="fa fa-align-justify"></i> Liste de mes adhésions
            </div>
            <div class="card-body">
                <table class="table table-responsive-sm table-bordered table-striped table-sm" id="adhesionTable">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Associaton</th>
                        @* <th>Utilisateur</th> *@
                        <th>Date de début</th>
                        <th>Date de fin</th>
                        <th>Status</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var adhesion in Model)
                    {
                        <tr>
                            <td>@adhesion.Id</td>
                            <td>@adhesion.Association.Nom</td>
                            <td>@adhesion.DateDebut</td>
                            <td>@adhesion.DateFin</td>
                            @* <td>@adhesion.Statut</td> *@
                            <td>
                                <span class="badge badge-success">Active</span>
                            </td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- /.col-->
</div>

@section Scripts
{
    <script>
        $(document).ready( function () {
            $('#adhesionTable').DataTable();
        } );
    </script>
}

AssoFlex/Views/Utilisateur/GetCrowdfundings.cshtml
@model List<Contribution>

@{
    ViewBag.Title = "Mes Crowdfundings";
    Layout = "_LayoutDashboard";
}
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <i class="fa fa-align-justify"></i> Liste de mes crowdfundings
            </div>
            <div class="card-body">
                <table class="table table-responsive-sm table-bordered table-striped table-sm" id="crowdfundingTable">
                    <thead>
                    <tr>
                        <th>ID</th>
                        @* <th>Nom</th> *@
                        @* <th>Utilisateur</th> *@
                        <th>Montant</th>
                        @* <th>Montant encours</th> *@
                        @* <th>Ma participation</th> *@
                        <th>Date </th>
                        @* <th>Data de fin</th> *@
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var contribution in Model)
                    {
                        <tr>
                            <td>@contribution.Id</td>
                            <td>@contribution.MontantContribution</td>
                            <td>@contribution.DateContribution</td>
                            @* <td>@crowdfunding.DateDebutProjet</td> *@
                            @* <td>@crowdfunding.DateFinProjet</td> *@
                            @* <td>@adhesion.Statut</td> *@
                            <td>
                                <span class="badge badge-success">Active</span>
                            </td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- /.col-->
</div>

@section Scripts
{
    <script>
        $(document).ready( function () {
            $('#crowdfundingTable').DataTable();
        } );
    </script>
}

AssoFlex/Views/Utilisateur/GetEvenements.cshtml
@model List<Reservation>

@{
    ViewBag.Title = "Mes évènements";
    Layout = "_LayoutDashboard";
}
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <i class="fa fa-align-justify"></i> Liste de mes évènements
            </div>
            <div class="card-body">
                <table class="table table-responsive-sm table-bordered table-striped table-sm" id="crowdfundingTable">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nom</th>
                        @* <th>Utilisateur</th> *@
                        @* <th>Organisateur</th> *@
                        @* <th>Montant encours</th> *@
                        @* <th>Ma participation</th> *@
                        <th>Date de début</th>
                        <th>Date de fin</th>
                        <th>Status</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var reservation in Model)
                    {
                        <tr>
                            <td>@reservation.Id</td>
                            <td>@reservation.Event.NomEvent</td>
                            @* <td>@reservation.Event.Organisateur.Nom</td> *@
                            <td>@reservation.Event.DateDebutEvent</td>
                            <td>@reservation.Event.DateFinEvent</td>
                            @* <td>@evenement.Reservation</td> *@
                            @* <td>@adhesion.Statut</td> *@
                            <td>
                                <span class="badge badge-success">Active</span>
                            </td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- /.col-->
</div>

@section Scripts
{
    <script>
        $(document).ready( function () {
            $('#crowdfundingTable').DataTable();
        } );
    </script>
}

AssoFlex/Views/Utilisateur/GetUtilisateur.cshtml
@using System.Security.Claims
@using AssoFlex.Models
@model Utilisateur

@{
    ViewBag.Title = "Profil";
    Layout = "_LayoutDashboard";
}

<div class="container">
    <div class="row">
        <div class="col-lg-4">
            <div class="card shadow-sm">
                <div class="card-header bg-transparent text-center">
                    <img class="img-avatar" src="~/FileSystem/@Model.ProfilImg" alt="userAvatar">
                    <h3>@Model.Prenom @Model.Nom</h3>
                </div>
                @* <div class="card-body"> *@
                @*   <p class="mb-0"><strong class="pr-1">Student ID:</strong>321000001</p> *@
                @*   <p class="mb-0"><strong class="pr-1">Class:</strong>4</p> *@
                @*   <p class="mb-0"><strong class="pr-1">Section:</strong>A</p> *@
                @* </div> *@
            </div>
        </div>
        <div class="col-lg-8">
            <div class="card shadow-sm">
                <div class="card-header bg-transparent border-0">
                    <h3 class="mb-0"><i class="far fa-clone pr-1"></i>Informations Générales</h3>
                    @* <a class="btn btn-primary px-4" type="button" href=@Url.Action("UpdateUtilisateur","Utilisateur")>Modifier</a> *@
                </div>
                <div class="card-body pt-0">
                    <div class="form-floating mb-3">
                        @Html.LabelFor(model => model.Prenom)
                        @Html.DisplayFor(model => model.Prenom, new {@class = "form-control"})
                        @Html.ValidationMessageFor(model => model.Prenom)
                    </div>

                    <div class="form-floating mb-3">
                        @Html.LabelFor(model => model.Nom)
                        @Html.DisplayFor(model => model.Nom, new {@class = "form-control"})
                        @Html.ValidationMessageFor(model => model.Nom)
                    </div>

                    <div class="form-floating mb-3">
                        @Html.LabelFor(model => model.Adresse)
                        @Html.DisplayFor(model => model.Adresse, new {@class = "form-control"})
                        @Html.ValidationMessageFor(model => model.Adresse)
                    </div>

                    <div class="form-floating mb-3">
                        @Html.LabelFor(model => model.Telephone)
                        @Html.DisplayFor(model => model.Telephone, new {@class = "form-control"})
                        @Html.ValidationMessageFor(model => model.Telephone)
                    </div>

                    <div class="form-floating mb-3">
                        @Html.LabelFor(model => model.Email)
                        @Html.DisplayFor(model => model.Email, new {@class = "form-control"})
                        @Html.ValidationMessageFor(model => model.Email)
                    </div>

                    @* <div class="form-floating mb-3"> *@
                    @*     @Html.LabelFor(model => model.Password) *@
                    @*     @Html.DisplayFor(model => model.Password, new {@type = "password", @class = "form-control"}) *@
                    @*     @Html.ValidationMessageFor(model => model.Password) *@
                    @* </div> *@
                </div>
                <div class="card-footer bg-transparent border-0">
                    <button class="btn btn-primary px-4" type="button" data-toggle="modal" data-target="#largeModal">Éditer</button>
                </div>
            </div>
            <div style="height: 26px"></div>
            <div class="card shadow-sm">
                <div class="card-header bg-transparent border-0">
                    <h3 class="mb-0"><i class="far fa-clone pr-1"></i>Description</h3>
                </div>
                <div class="card-body pt-0">
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="largeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Modification Profil</h4>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    @using (Html.BeginForm("UpdateUtilisateur", "Utilisateur"))
                    {
                        <div class="form-floating mb-3">
                            @Html.LabelFor(model => model.Prenom)
                            @Html.TextBoxFor(model => model.Prenom, new {@class = "form-control", placeholder = "Prénom"})
                            @Html.ValidationMessageFor(model => model.Prenom)
                        </div>

                        <div class="form-floating mb-3">
                            @Html.LabelFor(model => model.Nom)
                            @Html.TextBoxFor(model => model.Nom, new {@class = "form-control", placeholder = "Nom"})
                            @Html.ValidationMessageFor(model => model.Nom)
                        </div>

                        <div class="form-floating mb-3">
                            @Html.LabelFor(model => model.Adresse)
                            @Html.TextBoxFor(model => model.Adresse, new {@class = "form-control", placeholder = "Adresse"})
                            @Html.ValidationMessageFor(model => model.Adresse)
                        </div>

                        <div class="form-floating mb-3">
                            @Html.LabelFor(model => model.Telephone)
                            @Html.TextBoxFor(model => model.Telephone, new {@class = "form-control", placeholder = "Téléphone"})
                            @Html.ValidationMessageFor(model => model.Telephone)
                        </div>

                        <div class="form-floating mb-3">
                            @Html.LabelFor(model => model.Email)
                            @Html.TextBoxFor(model => model.Email, new {@class = "form-control", placeholder = "Email"})
                            @Html.ValidationMessageFor(model => model.Email)
                        </div>

                        <div class="form-floating mb-3">
                             @Html.LabelFor(model => model.Password)
                            @Html.TextBoxFor(model => model.Password, new {@type = "password", @class = "form-control", placeholder = "Mot de passe"})
                            @Html.ValidationMessageFor(model => model.Password)
                        </div>
                        <div class="modal-footer">
                            <button class="btn btn-secondary" type="button" data-dismiss="modal">Fermer</button>
                            <button class="btn btn-primary" type="submit">Sauvegader</button>
                        </div>
                    }
                </div>
            </div>
        </div>
        <!-- /.modal-dialog-->
    </div>
</div>

AssoFlex/Views/Utilisateur/UpdateUtilisateur.cshtml
@model AssoFlex.Models.Utilisateur

@{
    ViewBag.Title = "Modification Profil";
    Layout = "_LayoutDashboard";
}
<section class="page-section portfolio mt-5">
    <div class="container">
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Création de compte</h2>
        <!-- Icon Divider-->
        @* <div class="divider-custom"> *@
        @*     <div class="divider-custom-line"></div> *@
        @*     <div class="divider-custom-icon"><i class="fas fa-star"></i></div> *@
        @*     <div class="divider-custom-line"></div> *@
        @* </div> *@
        <div class="row justify-content-center">
            <div class="col-lg-8 col-xl-7">
                @using (Html.BeginForm())
                {
                    <div class="form-floating mb-3">
                        @Html.TextBoxFor(model => model.Prenom, new {@class = "form-control", placeholder = "Prénom"})
                        @Html.LabelFor(model => model.Prenom)
                        @Html.ValidationMessageFor(model => model.Prenom)
                    </div>

                    <div class="form-floating mb-3">
                        @Html.TextBoxFor(model => model.Nom, new {@class = "form-control", placeholder = "Nom"})
                        @Html.LabelFor(model => model.Nom)
                        @Html.ValidationMessageFor(model => model.Nom)
                    </div>

                    <div class="form-floating mb-3">
                        @Html.TextBoxFor(model => model.Adresse, new {@class = "form-control", placeholder = "Adresse"})
                        @Html.LabelFor(model => model.Adresse)
                        @Html.ValidationMessageFor(model => model.Adresse)
                    </div>

                    <div class="form-floating mb-3">
                        @Html.TextBoxFor(model => model.Telephone, new {@class = "form-control", placeholder = "Téléphone"})
                        @Html.LabelFor(model => model.Telephone)
                        @Html.ValidationMessageFor(model => model.Telephone)
                    </div>

                    <div class="form-floating mb-3">
                        @Html.TextBoxFor(model => model.Email, new {@class = "form-control", placeholder = "Email"})
                        @Html.LabelFor(model => model.Email)
                        @Html.ValidationMessageFor(model => model.Email)
                    </div>

                    <div class="form-floating mb-3">
                        @Html.TextBoxFor(model => model.Password, new {@type = "password", @class = "form-control", placeholder = "Mot de passe"})
                        @Html.LabelFor(model => model.Password)
                        @Html.ValidationMessageFor(model => model.Password)
                    </div>
                    <!-- Submit Button-->
                    <button class="btn btn-primary btn-xl" type="submit">Sauvegarder</button>
                }
            </div>
        </div>
    </div>
</section>